import io
import zipfile
from pathlib import Path
from config import SESSION_DIR


def create_package(session_id: str, artifacts: dict) -> str:
    """
    Package all pipeline artifacts into a downloadable ZIP file.
    """
    zip_path = SESSION_DIR / session_id / "pipeline_package.zip"
    zip_path.parent.mkdir(parents=True, exist_ok=True)

    buffer = io.BytesIO()
    with zipfile.ZipFile(buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        # ETL Script
        if artifacts.get("etl_code"):
            zf.writestr("etl_pipeline.py", artifacts["etl_code"])

        # SQL Schema
        if artifacts.get("sql_schema"):
            zf.writestr("schema.sql", artifacts["sql_schema"])

        # Airflow DAG
        if artifacts.get("airflow_dag"):
            zf.writestr("dags/pipeline_dag.py", artifacts["airflow_dag"])

        # Docker Compose
        docker_compose = artifacts.get("docker_compose", "") or _default_docker_compose()
        zf.writestr("docker-compose.yml", docker_compose)

        # README
        readme = artifacts.get("readme", "") or _default_readme(session_id)
        zf.writestr("README.md", readme)

        # Requirements for the generated pipeline
        zf.writestr("requirements.txt", "pandas\\npsycopg2-binary\\nsqlalchemy\\napache-airflow\\n")

    with open(zip_path, "wb") as f:
        f.write(buffer.getvalue())

    return str(zip_path)


def _default_docker_compose() -> str:
    return """version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: pipeline_db
      POSTGRES_USER: pipeline_user
      POSTGRES_PASSWORD: pipeline_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  airflow-webserver:
    image: apache/airflow:2.8.1
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://pipeline_user:pipeline_pass@postgres/pipeline_db
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    depends_on:
      - postgres

volumes:
  pgdata:
"""


def _default_readme(session_id: str) -> str:
    return f"""# Auto-Generated Data Pipeline

**Session ID:** {session_id}

## Quick Start

1. **Install dependencies:**
   ```bash
   pip install -r requirements.txt
   ```

2. **Start infrastructure:**
   ```bash
   docker-compose up -d
   ```

3. **Run ETL manually:**
   ```bash
   python etl_pipeline.py
   ```

4. **Deploy to Airflow:**
   Copy `dags/pipeline_dag.py` to your Airflow DAGs folder.

## Files

| File | Description |
|------|-------------|
| `etl_pipeline.py` | Main ETL transformation script |
| `schema.sql` | PostgreSQL schema DDL |
| `dags/pipeline_dag.py` | Airflow DAG for scheduling |
| `docker-compose.yml` | Docker setup for PostgreSQL + Airflow |

## Generated by Self-Healing Pipeline Agent
This pipeline was automatically generated, simulated, and healed by an AI agent.
"""
